---
title: "Dining Safety in Manhattan: Analyzing Manhattan Restaurant Hygiene Ratings"
output: 
  html_document:
    code_folding: hide
    always_allow_html: true
    toc: true
    toc_float: true
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, message = FALSE)
```
*Katherine Wang(dw3093), Ruicong Du(rd3096), Yining He(yh3683), Qianxuan Huang(qh2285), Wentao Zhou (wz2722)*

## **Motivation**

The motivation for this research is to evaluate food safety practices in Manhattan through the New York City Department of Health and Mental Hygiene (DOHMH) Restaurant Inspection Results dataset. This dataset includes critical variables such as inspection scores, grades, and violation descriptions, providing a foundation for analyzing trends and identifying common issues in restaurant hygiene. Our focus is to uncover patterns in food safety practices, highlight areas needing improvement, and identify restaurants that consistently meet high standards. By doing so, we aim to provide valuable insights for diners seeking safe and high-quality dining experiences and contribute to the ongoing efforts to maintain and improve public health standards in Manhattan's diverse dining landscape.

## **Related Work**

We were inspired to undertake this analysis after examining the [DOHMH Restaurant Inspection Results dataset](https://data.cityofnewyork.us/Health/DOHMH-New-York-City-Restaurant-Inspection-Results/43nn-pn8j/about_data) available on [NYC OpenData](https://opendata.cityofnewyork.us/). This dataset offers comprehensive details on restaurant inspections, including grades, scores, violation descriptions, and locations, making it an excellent resource for studying food safety practices and trends in Manhattan. Its depth and variety present a valuable opportunity to apply data visualization and interactivity techniques while addressing practical public health issues covered in our coursework.

## **Initial Questions**

Our initial questions focused on restaurant hygiene issues in Manhattan, aiming to help people identify restaurants that are both suitable for their taste preferences and meet high hygiene standards. We were interested in the following:

1. What is the most common cuisine type among restaurants in Manhattan, and what are their hygiene ratings?

2. Are there significant differences in inspection scores among different critical violations and location respectively?

3. Which cuisine types are more prone to critical health violations?

4. How are inspection grades (A, B, C) distributed across different part of Manhattan? 

5. How does the cuisine type, inspection type, violation type, location impact our overall hygiene grading?

## **Data**

This dataset is derived from the [DOHMH New York City Restaurant Inspection Results Dataset](https://data.cityofnewyork.us/Health/DOHMH-New-York-City-Restaurant-Inspection-Results/43nn-pn8j/about_data) and has been specifically processed to focus on restaurant inspection results from Manhattan for this project. It includes detailed records of health code violations, inspection grades, and scores from establishments in active status. 

To prepare the data for analysis, we performed the following cleaning steps:

Filtered the dataset to include only records where the (`BORO`) field corresponds to *Manhattan*.

Removed entries with missing critical fields, such as (`DBA`) (restaurant name), (`CUISINE`) (`DESCRIPTION`), (`SCORE`), or (`GRADE`).

Verified consistency in inspection dates and formatted them in date format.
Standardized continuous variables like (`SCORE`) to ensure numeric values were properly stored.

Ensured all categorical variables, such as (`GRADE`), were appropriately formatted and complete.


The final data used for analysis, saved [here](https://github.com/katherinewang0903/final_nyc_restaurant.github.io/blob/main/Manhattan_Restaurant_Inspection_Results.csv), contains 94,616 observations and includes the following variables:

* `CAMIS`: Unique identifier for each restaurant establishment.
* `DBA`: Doing Business As (DBA) name of the establishment.
* `BORO`: Borough where the establishment is located (Cleaned data we used only includes Manhattan).
* `BUILDING`: Building number where the establishment is located.
* `STREET`: Street name where the establishment is located.
* `ZIPCODE`: ZIP Code of the establishment.
* `PHONE`: Phone number of the establishment.
* `CUISINE DESCRIPTION`: Type of cuisine served by the establishment.
* `INSPECTION DATE`: Date of the most recent inspection.
* `ACTION`: Action taken based on the inspection results.
* `VIOLATION CODE`: Code for the specific health code violation.
* `VIOLATION DESCRIPTION`: Description of the health code violation.
* `CRITICAL FLAG`: Indicator for critical health violations.
* `SCORE`: Score assigned based on inspection results.
* `GRADE`: Grade assigned to the establishment (A, B, C, etc.).
* `GRADE DATE`: Date when the grade was assigned.
* `RECORD DATE`: Date when the record was created or updated.
* `INSPECTION TYPE`: Type of inspection conducted (initial, reinspection, etc.).
* `Latitude`: Latitude coordinate of the establishment.
* `Longitude`: Longitude coordinate of the establishment.
* `Community Board`: Community Board where the establishment is located.
* `Council District`: Council District where the establishment is located.
* `Census Tract`: Census Tract where the establishment is located.
* `BIN`: Building Identification Number.
* `BBL`: Borough-Block-Lot number.
* `NTA`: Neighborhood Tabulation Area of the establishment.
* `Location Point1`: Geographic location of the establishment.

## **Exploratory Analysis**

### [Demographics Analysis](https://katherinewang0903.github.io/final_nyc_restaurant.github.io/demographics.html)

For Demographics analysis, we focuses on the Manhattan’s restaurants across three dimensions: physical location, popular types of cuisine, and health inspection grades. The dataset was cleaned to include complete records, categorizing restaurants into three regions—Downtown, Midtown, and Uptown—based on ZIP codes. Restaurants graded as Z (Grade Pending), P (Pending Reopening), and N (Not Yet Graded) were excluded to ensure clarity and relevance in evaluating distribution patterns.

The Physical Location analysis provides an overview of restaurant locations across Manhattan, allowing us to see each restaurant’s name, cuisine type, geographic location, and health inspection grade. This distribution reflects how restaurants cluster in different areas. Midtown and Downtown Manhattan have a high concentration of restaurants, while Uptown Manhattan has significantly fewer establishments. This pattern can be attributed to several factors: Midtown and Downtown are bustling commercial hubs with higher population density, more office spaces, and greater tourism activity, all of which drive demand for dining options. In contrast, Uptown has a lower density of commercial spaces and fewer tourist attractions, resulting in less restaurant clustering.

Cuisine Type analysis reveals that American cuisine dominates with 2,456 establishments, followed by Chinese, Italian, and Japanese cuisines, which represent Manhattan's multicultural dining scene. Additionally, Coffee/Tea establishments rank prominently with over 1,000 locations, catering to the city’s fast-paced lifestyle. This breakdown highlights a wide diversity in dining options, with quick-service and globally inspired cuisines holding substantial market.

The Health Inspection Grade Distribution shows that most Manhattan restaurants maintain high hygiene standards, with Grade A being the most common, ranging from 50% to 80%. Coffee/Tea (80%) and French (70%) cuisines lead in hygiene compliance, while Bakery Products/Desserts (50%) have the lowest proportion of Grade A, highlighting room for improvement. Chinese and Japanese cuisines show greater variability, with higher proportions of lower grades (B and C) and pending grades (Z and P), suggesting specific challenges in meeting food safety standards. These results underscore the need for targeted interventions to support improved hygiene practices across all cuisine types.

---

### [Violations Analysis](https://katherinewang0903.github.io/final_nyc_restaurant.github.io/violations.html)

As for analysis related to violation, we  focuses exclusively on data where the grades are A, B, or C, and excludes records with grades labeled as N (Not Yet Graded), Z (Grade Pending), or P (Grade Pending issued upon reopening after a closure). We also exclude “Not Applicable” entries for critical violation indicators. Inspection violations are categorized into two groups: Critical and Not Critical. Critical violations represent the most significant risks for foodborne illnesses. To ensure accuracy and relevance, we begin by filtering out unnecessary data from the dataset before proceeding with the analysis.

First, we analyze the frequency distribution of grades. For both Critical and Not Critical groups, the majority of restaurants received a Grade A, followed by Grade B, and then Grade C. However, only within Grade A do we observe more restaurants with Not Critical violations compared to Critical violations. Additionally, when examining inspection scores across all grade categories, restaurants with Not Critical violations consistently achieve lower scores. This pattern aligns with the corresponding grade results, further highlighting the relationship between inspection outcomes and grade assignments.

Next, we conducted a Chi-Square Test to examine the relationship between the critical flag and grade. The results are visualized using a Contingency Table Heatmap. The analysis shows a p-value smaller than 0.05, leading us to reject the null hypothesis that the critical flag and grade are independent. This indicates a significant relationship between the critical flag and grade at the 0.05 significance level.

Among all restaurants with critical violations, we aimed to identify the most common types of violations. To achieve this, we calculated the percentage of each violation type and grouped all categories with less than 3% into an "Other" category for clarity. The results are summarized in a pie chart, providing a clear visualization of the distribution of critical violations. The analysis reveals that the most frequent critical violation is related to washing and temperature problem. These are more than a quarter in total percentage. This finding underscores the importance of proper temperature management and remain cleaning in ensuring food safety and reducing the risk of foodborne illnesses. Also, restaurants owner who want to avoid bad grade in inspection need to perticullar pay attention to them.

--- 

### [Location vs. Grade Analysis](https://katherinewang0903.github.io/final_nyc_restaurant.github.io/location.html)

In this chapter, we analyze the relationship between locations and grades. Our analysis focuses exclusively on data where the grades are `A`, `B`, or `C`, and excludes records with grades labeled as N (Not Yet Graded), Z (Grade Pending), or P (Grade Pending issued upon reopening after a closure). To ensure accuracy and relevance, we begin by filtering out unnecessary data from the dataset before proceeding with the analysis. The location is divided by `Financial District`, `Chinatown`, `West Village`, `Upper East Side`, `Upper West Side`, `Harlem`, `Washington Heights`, `East Village`, `Chelsea`, `Battery Park City`, `Bowery`, `SoHo`, `Gramercy Park`, `Flatiron District`, `Carnegie Hill`, `Tribeca`, `Governors Island`, `Midtown`, `Roosevelt Island`, `Other`.

To investigate if where restaurants are located influence their inspection grades, we produce `Chi-Square test`. The result is presented in the `Contingency Table Heatmap` below. The `Chi-Square statistics` is 584.26, and `p-value is less than 0.05`, leading us to reject the null hypothesis that `the region and grade are independent`. This indicates a there a significant difference in the distribution of grades among regions at the 0.05 significance level. <br>
The `Midtown` region exhibits the highest concentration of Grade A restaurants, as indicated by the darkest shade of purple. Other regions like `Upper East Side` and `Upper West Side` also show substantial numbers of Grade A restaurants. `Grades B and C` are less frequent across all regions, with the light shading indicating their relatively low counts.

To investigate how strong the association is between locations and grades, we produce `Cramér’s V test`. The `Cramér’s V Value is  0.085`, which is less than 0.1, so that we conclude locations and grades have `weak association`. This conclusion is visualized in the stacked bar charts below of different regions that we can't tell large difference among them.

This stacked bar chart illustrates the distribution of hygiene grades across various regions in Manhattan. Grade A, represented in blue, dominates most regions. In contrast, regions such as `Harlem` and `Washington Heights` show a slightly higher proportion of lower grades (B and C), indicating potential areas for improvement. Some regions, like `Roosevelt Island`, almost exclusively maintain grade A ratings, showcasing exceptional cleanliness. However, since only slightly differences among locations are shown, the result fits that the association is weak.

--- 

### [Cuisine Types Analysis](https://katherinewang0903.github.io/final_nyc_restaurant.github.io/cuisine.html)

The aim of this analysis is to evaluate restaurant hygiene trends across Manhattan, focusing on inspection scores and their variability by cuisine type and location. Using interactive visualizations, we identify patterns in hygiene performance and highlight areas and cuisines requiring improvement.

NYC restaurant inspections categorize hygiene performance into:
`Grade A`: Scores below 14, indicating excellent hygiene.
`Grade B`: Scores between 14 and 27, showing acceptable hygiene.
`Grade C`: Scores of 28 or higher, suggesting poor hygiene.

Density Map of Inspection Scores
<br> The interactive density map, created with plot_ly, visualizes average restaurant inspection scores across Manhattan. Data was filtered to include valid latitude, longitude, and inspection scores. A Viridis color scale highlights score variations from 0 (best) to 40 (worst). Users can click on points to view specific scores by location, enhancing interactivity and offering a geographic perspective on hygiene trends.

Top 35 Cuisine Types by Average Inspection Scores
<br> This bar chart ranks the top 35 cuisine types by their average inspection scores. Using data grouped by `CUISINE DESCRIPTION`, we calculated mean scores and visually represented them with orange bars and purple borders. Cuisines like Bangladeshi, African, and Filipino have the highest average scores, indicating hygiene challenges, while cuisines such as Japanese and Mediterranean rank lower, reflecting better hygiene. This highlights cuisines that may benefit from targeted interventions.

Inspection Score Distribution for Top 35 Cuisine Types
<br> The boxplot illustrates the variability in inspection scores among the top 35 cuisines. Data was filtered to include only these cuisines, and boxplots were generated to display ranges, interquartile ranges (IQR), and outliers. Cuisines like Bangladeshi and African show wide score ranges and higher medians, suggesting inconsistent hygiene performance. In contrast, Japanese and Mediterranean cuisines exhibit narrow distributions with lower medians, indicating more consistent hygiene standards. This complements the bar chart by providing deeper insight into score variability.

### [Distribution Analysis](https://katherinewang0903.github.io/final_nyc_restaurant.github.io/distributionpage.html)

We analyzed how restaurant grades have evolved over time, focusing on neighborhoods and cuisine types, with Italian restaurants as a case study to evaluate trends within a specific cuisine.

The first line chart shows hygiene grade trends across Manhattan restaurants. Grade `A` dominates, with a sharp rise around 2022, likely due to improved hygiene practices or policy changes. Grades `B` and `C` increased slightly post-2020 but remain much lower, while other grades (`N`, `P`, `Z`) are minimally represented, emphasizing the focus on achieving grade `A`. 

The second line chart shows grade trends for Italian restaurants, highlighting a similar sharp rise in grade `A` around 2022. Grades `B` and `C` showed slight increases but remained infrequent, while other grades were rarely observed. This trend reflects a strong emphasis on maintaining high cleanliness standards among Italian restaurants.

Univariable Ordinal Regression
<br> We conducted a univariable ordinal regression to examine the relationship between restaurant grades (`A`, `B`, `C`) and predictors like `cuisine type`, `inspection type`, `violation code`, and `location`. Grades were converted to numeric values (`1` for `A`, `2` for `B`, `3` for `C`) for ordinal modeling. Positive estimates indicated a tendency toward poorer grades, while negative estimates reflected better grades. `P-values` assessed the significance of these associations. To enhance interpretation, we showcased the top 10 results, highlighting the strongest associations. For instance, `African` and `Asian/Asian Fusion` cuisines had statistically significant positive associations with poorer grades, offering insights for further exploration.

Residual Diagnostics
<br> We performed residual diagnostics on a generalized linear model (`GLM`) with a `quasipoisson` family to handle overdispersion. The `Q-Q plot` of residuals showed most data points aligning with the purple reference line, indicating normality. However, deviations at the tails suggest potential outliers or non-normality in extreme values. While the model fits well overall, further adjustments may address these discrepancies to improve fit.

## **Shiny app**

The Shiny app [HERE](https://katherinewang0903.shinyapps.io/shinyapp/) provides an interactive platform for exploring Manhattan's restaurant inspection data by allowing users to filter by region, cuisine type, and hygiene grade. The provided neighborhoods include the Financial District, Chinatown, West Village, Upper East Side, Upper West Side, Harlem, Washington Heights, East Village, Chelsea, Battery Park City, Bowery, SoHo, Gramercy Park, Flatiron District, Carnegie Hill, Tribeca, Governors Island, Midtown, and Roosevelt Island. Once filters are applied, all matching restaurants are displayed as clickable points on an interactive map.

When users click on a specific point, a popup box appears, providing detailed information about the restaurant, including its name, cuisine type, inspection grade, hygiene score, and neighborhood region. This interactive feature makes it convenient for users to visually analyze restaurant distribution, hygiene trends, and specific options available in their selected area. The map interface, combined with the filtering functionality, offers an engaging and user-friendly way to understand the restaurant hygiene landscape in Manhattan.

## **Discussion**

Our analysis of the NYC Department of Health and Mental Hygiene’s Restaurant Inspection Results dataset revealed several critical findings about restaurant hygiene and compliance within Manhattan. One notable discovery was the variation in inspection scores across different neighborhoods, highlighting areas with more frequent critical violations. This suggests the need for targeted interventions in specific locations to ensure food safety standards are upheld. Additionally, our exploration into cuisine types indicated that certain food preparation styles are associated with higher or lower hygiene scores, shedding light on potential risks tied to specific cuisines.

Another significant trend was the impact of critical violations on restaurant grades. Restaurants with repeated critical violations often received lower grades, emphasizing the importance of promptly addressing such issues to maintain customer trust and public health standards. Interestingly, we also observed fluctuations in overall hygiene compliance over time, potentially reflecting changes in enforcement practices or restaurant management priorities.

Recent news articles have supported these findings, with reports indicating a decline in the frequency of health inspections due to staffing shortages. According to [CBS News](https://www.cbsnews.com/newyork/news/nyc-restaurant-health-inspections-2023-2024/) about NYC Manhattan restaurant health inspections. Health inspections in Mahanttan have decreased by 17% in the past year, raising concerns about consistent enforcement of safety standards. This aligns with our observations of varying compliance levels, reinforcing the critical need for consistent oversight. By addressing these issues and promoting better compliance across all establishments, Manhattan’s dining scene can remain both vibrant and safe for all patrons.

## **References**

1.  <https://data.cityofnewyork.us/Health/DOHMH-New-York-City-Restaurant-Inspection-Results/43nn-pn8j/about_data>
2. <https://www.cbsnews.com/newyork/news/nyc-restaurant-health-inspections-2023-2024/>

Go [Home](index.html)